### ISSUE TITLE
Filenames sorting doesn't handle the case of identical names or last modified dates

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#156]
Steps to reproduce: 
1, Select a set of files with different names but equal last modified date values;
2. Select "SORT BY DATE" in the appeared dialog.
Current result: file names are equal.
Expected result: sorting by date should not be available, the corresponding message should be shown

The case with equal names but different last modified date values should be handled analogically.

In case both sorting keys have equal values, an error message should be displayed informing that selected filenames cannot be processed.

**Comment by lwp-vinokurova** [comment]
Tested 2021-07-26
- when last modified date values are equal for several files -> notification thet file can be sorted only by name is displayed, files are automatically sorted by name
- when both name and modification date differ - both sortings are available
- if the sorting by name and date are the same -> no sorting is proposed for the user 

- skipped case with identical names because file system do not allow to create 2 files with the same mane
