### ISSUE TITLE
Found 4 intervals while no intervals should have been found

### ISSUE THREAD

**Issue by Andrej-Adamenko** [lwp-emelnik/musicintervals2anki#2]
I tried to specify several different values for the start note , but the result was the same. It seem to ignore the start note value, when it does the search.
![Screenshot_20210107-132518_MusicIntervals2Anki.jpg](https://user-images.githubusercontent.com/70955223/103887857-71ff6900-50ec-11eb-83c9-36e74ef2dce4.jpg)
![Screenshot_20210107-133018_MusicIntervals2Anki.jpg](https://user-images.githubusercontent.com/70955223/103887888-7f1c5800-50ec-11eb-8913-a9fcbb952177.jpg)

**Comment by lwp-ygavrilenko** [comment]
The issue is caused by the discrepancy between the note type fields defined in the local AnkiDroid installation and expected fields of the default model. 
The most recent changes (#5) have added the model validation and respective error message, which should resolve the issue for the time being. 
A new ticket (#6) was created to implement explicit model fields configuration.
