### ISSUE TITLE
Validate fields in the same order as they are located

### ISSUE THREAD

**Issue by lwp-vinokurova** [lwp-emelnik/musicintervals2anki#200]
**Actual Result:** If several required fields are missed on "Add to AnkiDroid" button click they are checked in a random order.
(Octave, Interval, Start note, File, Timing, Instrument, Direction)

**Expected Result:** Validate fields in the same order as they are located 
(File, Start note, Octave, Direction, Timing, Interval, Instrument)

**Comment by lwp-ygavrilenko** [comment]
While we could first check the presence of any positive non-zero number of values for the "Filename" field, I don't think it makes much sense since we'll have to validate its count again once the user has filled multiple selection fields ("Start note", "Octave", "Interval"). As such, I think the current "multiple selection fields -> Filename -> single value fields" validation flow is sufficient.
Nevertheless, I've made some improvements to the pre-adding validation (including separately ordering the multiple selection fields validation & single value fields validation).

**Comment by lwp-vinokurova** [comment]
Tested. Fields are checked now in the following order:
1. multiple selection fields
2. file(s)
3. single value fields

Tested validation for adding single file, multiple files
